import Head from 'next/head';
import { useState } from 'react';

// icons
import { BsFillMoonStarsFill } from 'react-icons/bs';

// utils
import ProjectsSection from '../sections/ProjectsSection/projectsSection';
import MyTechStackSection from '../sections/MyTechStackSection/myTechStack';
import IntroductionSection from '../sections/IntroductionSection/introductionSection';

const Home = () => {
  // state
  const [darkMode, setDarkMode] = useState(false);

  // function
  const handleResumeDownload = () => {
    const resumePath = '/resume.pdf'; // Update with the correct filename

    const link = document.createElement('a');
    link.href = resumePath;
    link.download = 'MuhammadAniqMir-resume.pdf'; // Specify the desired download filename
    link.click();
  };

  return (
    // main container
    <div className={darkMode ? 'dark' : ''}>
      {/* head section */}
      <Head>
        <title>
          Muhammad Aniq Mir | Software Engineer | Front End Developer
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          {/* nav section */}
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='font-burtons text-xl'>developedbyaniq</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=' cursor-pointer text-2xl hover:animate-spin'
                />
              </li>
              <li>
                <button
                  className='hover:animate-pulse bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8'
                  onClick={handleResumeDownload}
                >
                  Resume
                </button>
              </li>
            </ul>
          </nav>

          {/* introduction section */}
          <IntroductionSection darkMode={darkMode} />
        </section>

        {/* tmy tech stack section */}
        <MyTechStackSection darkMode={darkMode} />

        {/* projects section */}
        <ProjectsSection darkMode={darkMode} />
      </main>
    </div>
  );
};

export default Home;
